services:
  postgres:
    image: postgres:17
    container_name: exury-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: exury_db
    ports:
      - "5432:5432"
    volumes:
      - exury_pgdata:/var/lib/postgresql/data

volumes:
  exury_pgdata:
